name: Compile and deploy

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build PDF with the Pandoc/LaTeX engine in Docker
        uses: ftsrg/document-converter-actions@master
      - name: Build HTML with the pandoc/core Docker image
        uses: docker://pandoc/core:2.14
        with:
          args: "--mathjax --standalone --from markdown+latex_macros bfs.md --output bfs.html"
      - name: Prepare for deployment
        run: |
          mkdir out
          cp *.html out/
          cp *.pdf out/
          echo "https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA" > out/README.md
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: out
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
