name: Compile and deploy

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Compile HTML
        uses: docker://pandoc/core:2.9
        with:
          args: "--mathjax --standalone --from markdown+latex_macros bfs.md --output bfs.html"
      - name: Compile PDF
        uses: docker://pandoc/latex:2.9
        with:
          args: "--from markdown+latex_macros bfs.md --output bfs.pdf --template eisvogel"
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: output
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
