name: Compile and deploy

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build PDF and HTML with the Pandoc/LaTeX engine in Docker
        uses: ftsrg/document-converter-actions@master
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: output
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
